#!/usr/bin/env bash

PROJECT=$GOPATH/src/github.com/jbrukh/ggit
cd $PROJECT
export PATH=$GOPATH/bin:$PROJECT/bin:$PATH

# not necessary if you're using the git hook
# at https://github.com/jbrukh/git-gofmt or
# if you have GoSublime for Sublime Text 2
alias gf="gofmt -tabs=false -tabwidth=4 -w *.go"

# the most up-to-date ggit command
alias gg="go run $GOPATH/src/github.com/jbrukh/ggit/cmd/ggit/*.go"

ggbench-csv() {
	SHA=`git rev-parse HEAD`
	ggbench | grep Benchmark | sed -E -e "s/[ 	]+/,/g" | sed -e "/FAIL:/d" -e "s/^/$SHA,/g" -e "s/$/,$1/g"
}

ggbench-range() {
	set -e
	HEAD=`git rev-parse HEAD`
	revlist=`git rev-list --max-count=10 --reverse HEAD`
	for sha in $revlist; do
		git checkout $sha >/dev/null 2>&1
		if [ $? -ne 0 ]
		then
			echo "checkout failed: $sha"
			return 1
		fi
		ggbuild && ggbench-csv 1 2>&1
		if [ $? -ne 0 ]
		then
			echo "ggbench failed: $sha"
			return 1
		fi
	done
	git checkout $HEAD
}

# list some objects... this is slow, so use on small repos
objects() {
    for o in `ggit ls-objects`; do echo $o `ggit cat-file -t $o`; done
}

compare() {
	echo "GIT ==========================="
	git "$@"
	echo "GGIT =========================="
	ggit "$@"
	echo "==============================="
}

ggtime() {
	echo "GIT ==========================="
	time git "$@" 2>&1 >/dev/null
	echo "GGIT =========================="
	time ggit "$@" 2>&1 >/dev/null
	echo "==============================="
}
	
